name: Publish on Github, Curseforge & Modrinth

on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.19.3
  JAVA_VERSION: 17
  VERSION: 1.19.3-3.0.2
  RELEASE_NAME: Forgotten Graves 1.19.3-3.0.2
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth/Github)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 550480
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: FrZIkosK
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
          files-secondary: ""

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"